version: 2.1

orbs:
  test-ansible-galaxy-role:
    executors:
      default:
        docker:
          - image: 'circleci/python:3-stretch'

    jobs:
      syntax-check:
        parameters:
          ansible-version:
            type: string
        executor: default
        steps:
          - run: python --version
          - checkout
          # TODO: Cache pip OR install via apt-get.
          - run: sudo pip install ansible<< parameters.ansible-version >>
          - run: ansible --version
          - run: ansible-playbook -i 'localhost,' --syntax-check tests/test.yml

      lint:
        executor: default
        steps:
          - run: python --version
          - checkout
          # TODO: Cache pip OR install via apt-get.
          - run: sudo pip install ansible-lint
          - run: ansible-lint --version
          - run: ansible-lint tests/test.yml

workflows:
  lint:
    jobs:
      - test-ansible-galaxy-role/lint
  syntax-check:
    jobs:
      - test-ansible-galaxy-role/syntax-check:
          name: syntax-check-ansible-latest
          ansible-version: ''
      - test-ansible-galaxy-role/syntax-check:
          name: syntax-check-ansible-2.9
          ansible-version: ~=2.9.0
      - test-ansible-galaxy-role/syntax-check:
          name: syntax-check-ansible-2.8
          ansible-version: ~=2.8.0
      - test-ansible-galaxy-role/syntax-check:
          name: syntax-check-ansible-2.7
          ansible-version: ~=2.7.0
